# Generated by Django 3.2.9 on 2022-02-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0002_auto_20220209_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
    ]
